# Header
menu:
  Home: /
  About: /about
  Archives: /archives

# Title on top left of menu. Leave empty to use main blog title
menu_title:

# URL of the Home page image
index_cover: /img/home-bg.jpg

# Default post title
default_post_title:

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: davidkassa

# Google Analytics Tracking ID
google_analytics:

# Addthis ID
addthis:

# set your own favicon
favicon: /favicon.ico

# Social Accounts
twitter_url: https://twitter.com/dmkassa
twitter_handle: dmkassa
facebook_url: https://www.facebook.com/david.kassa
github_url: https://github.com/davidkassa
gitlab_url: https://gitlab.com/davidkassa
linkedin_url: https://www.linkedin.com/in/davidkassa
mailto: david.kassa@gmail.com
